version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: node-app
    ports:
      - "8889:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: tester-node-app
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run","test"]