name: Docker Image CI

on:
  push:
    branches: [ "my_testing" ]
  pull_request:
    branches: [ "my_testing" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag preprod-testing-image:$(date +%s)

