name: "Release new Image"

on:
  pull_request:
    types:
        - closed
    branches: [main]

jobs:
    if_merged:
        if:  github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker build . --file Dockerfile --tag asheer/node-uat-testing:latest
          - run: docker run -e CI=true  asheer/node-uat-testing:latest npm run test -- --coverage
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'

            
          - name: Deploy 2 EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                application_name: react-app
                environment_name: React-app-env
                existing_bucket_name: ${{ secrets.ASS3_BUCKET }}
                region: us-east-1
                version_label: ${{ github.sha }}
                use_existing_version_if_available: true
                deployment_package: deploy.zip

        # - name: Log in to Docker Hub
        #   uses: docker/login-action@v1
        #   with:
        #     username: ${{ secrets.DOCKER_USERNAME }}
        #     password: ${{ secrets.DOCKER_PASSWORD }}  
        # - name: Docker Push
        #   run: docker push ${{secrets.DOCKER_USERNAME}}/node-uat-testing

        